export const timelineData = [
  {
    year: '1969',
    location: 'Williams Lake',
    name: 'Gloria Moody',
    blurb: 'Gloria went out one night with her brother only to disappear behind him on their way home.',
    link: 'https://thehueandcry.com/gloria-moody',
    photo: 'https://wordpress.thehueandcry.com/wp-content/uploads/gloria-moody.jpeg',
  },
  {
    year: '1970',
    location: "Hudson's Hope",
    name: 'Micheline Pare',
    blurb: "Micheline was 18 years old when she went missing along Highway 16.",
    link: 'https://thehueandcry.com/micheline-pare',
    photo: 'https://wordpress.thehueandcry.com/wp-content/uploads/micheline-pare.png',
  },
  {
    year: '1970',
    location: "Prince George",
    name: 'Helen Claire Frost',
    blurb: "Helen disappeared just four days before her 18th birthday. She was last seen leaving the apartment she shared with her sister, telling her sister she wanted to go for a quick walk. She never returned home.",
    photo: 'https://wordpress.thehueandcry.com/wp-content/uploads/helen-claire-frost.jpeg',
  },
  {
    year: '1971',
    location: "Gitsegukla",
    name: 'Jean Virginia Sampare',
    blurb: 'Jean was last seen by her cousin on the railroad overpass on Highway 16. Her cousin had left her momentarily to retrieve an item from his house. When he came back to the area, Jean was gone. She was never seen again.',
    photo: 'https://wordpress.thehueandcry.com/wp-content/uploads/Jean_Virginia_Sampare.png',
  },
  {
    year: '1974',
    location: "Thornhill",
    name: 'Monica Ignas',
    blurb: 'Monica was only 14 years old and was last seen walking home on Highway 16 in the direction of her house.',
    link: 'https://thehueandcry.com/monica-ignas',
    photo: 'https://wordpress.thehueandcry.com/wp-content/uploads/monica-ignas.png',
  },
  {
    year: '1978',
    location: "Prince Rupert",
    name: 'Mary Jane Hill',
    blurb: 'Mary Jane Hill was 31 years old and a mother of three. Her body was found nude along Highway 16 and her death was deemed to be from bronchitis and bronchopneumonia as a result of manslaughter. ',
    photo: 'https://wordpress.thehueandcry.com/wp-content/uploads/mary-jane-hill.png',
  },
  {
    year: '1989',
    location: "Prince George",
    name: 'The Jack Family',
    blurb: 'Doreen Jack and her husband Ronald were offered jobs at a logging camp from an unknown man. The struggling family of four accepted the job and ride the man offered. The family was last seen at 1:20am that night leaving with the man in his car.',
    photo: 'https://wordpress.thehueandcry.com/wp-content/uploads/doreen-jack.jpeg',
  },
  {
    year: '1989',
    location: "Prince Rupert",
    name: 'Alberta Williams',
    blurb: 'Alberta Williams was 24 years old when she was last seen leaving a bar in Prince Rupert.',
    link: 'https://thehueandcry.com/alberta-williams',
    photo: 'https://i0.wp.com/wordpress.thehueandcry.com/wp-content/uploads/alberta-williams-photo.jpg?fit=656%2C611&ssl=1',
  },
  {
    year: '1990',
    location: "Smithers",
    name: 'Delphine Nikal',
    blurb: 'Delphine Nikal was last seen leaving her group of friends one night to head home, but never made it back.',
    link: 'https://thehueandcry.com/delphine-nikal',
    photo: 'https://i0.wp.com/wordpress.thehueandcry.com/wp-content/uploads/delphine-nikal-poster.jpg?fit=656%2C611&ssl=1',
  },
  {
    year: '1994',
    location: "Smithers",
    name: 'Ramona Wilson',
    blurb: 'Ramona Wilson was last seen on a Saturday night leaving her house to meet friends for a night out. No one has seen her since.',
    link: 'https://thehueandcry.com/ramona-wilson',
    photo: 'https://i0.wp.com/wordpress.thehueandcry.com/wp-content/uploads/ramona-wilson-photo-1.jpg?fit=656%2C611&ssl=1',
  },
  {
    year: '1994',
    location: "Prince George",
    name: 'Roxanne Thiara',
    blurb: 'Roxanne was 15 years old when she disappeared from Prince George on a long weekend in July.',
    link: 'https://thehueandcry.com/roxanne-thiara',
    photo: 'https://i0.wp.com/wordpress.thehueandcry.com/wp-content/uploads/roxanne-thiara-photo.jpeg?fit=656%2C611&ssl=1',
  },
  {
    year: '1994',
    location: "Prince George",
    name: 'Alisha Germaine',
    blurb: '15-year-old Alishia Germaine was last seen leaving a Christmas party in Prince Rupert.',
    link: 'https://thehueandcry.com/alishia-germaine',
    photo: 'https://i0.wp.com/wordpress.thehueandcry.com/wp-content/uploads/alishia-germaine.jpg?fit=543%2C611&ssl=1',
  },
  {
    year: '1995',
    location: "Terrace",
    name: 'Lana Patricia Derrick',
    blurb: 'Lana Patricia Derrick came home from college for Thanksgiving, but mysteriously disappeared after a night out.',
    link: 'https://thehueandcry.com/lana-derrick',
    photo: 'https://i0.wp.com/wordpress.thehueandcry.com/wp-content/uploads/lana-derrick.jpg?fit=656%2C611&ssl=1',
  },
  {
    year: '2002',
    location: "Prince George",
    name: 'Nicole Hoar',
    blurb: 'Nicole was working as a tree planter and was last seen at a gas station on Highway 16, hitchhiking from Prince George to Smithers.',
    photo: 'https://wordpress.thehueandcry.com/wp-content/uploads/nicole-hoar.jpeg',
  },
  {
    year: '2004',
    location: "Prince Rupert",
    name: 'Kayla Rose McKay',
    blurb: 'Kayla was 13 years old when she went missing from Prince Rupert. Her body was found two days later near train tracks on a waterfront on George Hills Way.',
    photo: 'https://wordpress.thehueandcry.com/wp-content/uploads/kayla-mckay.jpeg',
  },
  {
    year: '2004',
    location: "Fraser Lake",
    name: 'Margaret Nooski',
    blurb: 'Maragret was 89 years old when she went missing and was last seen hitchhiking on Highway 16. Police believe she may have been trying to get to Prince George, or headed into the bush in search of trapping territory.',
    photo: 'https://wordpress.thehueandcry.com/wp-content/uploads/unknown-image.png',
  },
  {
    year: '2005',
    location: "Prince Rupert",
    name: 'Tamara Chipman',
    blurb: 'Tamara was a young mother who disappeared after hitchhiking from Prince Rupert to Terrace in 2015.',
    link: 'https://thehueandcry.com/tamara-chipman',
    photo: 'https://i0.wp.com/wordpress.thehueandcry.com/wp-content/uploads/tamara-chipman-photo.jpg?fit=656%2C611&ssl=1',
  },
  {
    year: '2005',
    location: "Prince George",
    name: 'Mary Madeline George',
    blurb: 'Mary was last seen in the evening of July 24, 2005 at 6pm. She was walking from Ospika Blvd. to the Spruceland Mall Walk-in Clinic.',
    photo: 'https://wordpress.thehueandcry.com/wp-content/uploads/mary-madeline-george.jpeg',
  },
  {
    year: '2006',
    location: "Prince George",
    name: 'Aielah Katerina Saric-Auger',
    blurb: 'Aielah Saric-Auger was 14 years old when she went missing and was last seen along Highway 16.',
    link: 'https://thehueandcry.com/aielah-saric-auger',
    photo: 'https://i0.wp.com/wordpress.thehueandcry.com/wp-content/uploads/aielah-auger.jpg?fit=1200%2C722&ssl=1',
  },
  {
    year: '2007',
    location: "Vanderhoof",
    name: 'Bonnie Marie Joseph',
    blurb: 'Bonnie was a mother of five and was last seen hitchhiking from Vanderhoof to Prince George to attend a court date. She missed the appointment and was not heard from again. Her wallet, ID, and an uncashed cheque were found near a lake.',
    photo: 'https://wordpress.thehueandcry.com/wp-content/uploads/bonnie-joseph.png',
  },
  {
    year: '2010',
    location: "Prince Rupert",
    name: 'Emmalee Rose Mclean',
    blurb: 'Emma was 16 years old when she was last seen out with a group of people the night before she went missing. Her body was discovered along the Prince Rupert waterfront.',
    photo: 'https://wordpress.thehueandcry.com/wp-content/uploads/emma-rose.png',
  },
  {
    year: '2013',
    location: "Tachie",
    name: 'Immaculate "Mackie" Mary Basil',
    blurb: "Mackie was the mother of a five year old son. She went to a house party and never came back. She was last seen after the party heading to a cabin in the Leo Creek area.",
    photo: 'https://wordpress.thehueandcry.com/wp-content/uploads/Immaculate_Basil.jpeg',
  },
  {
    year: '2014',
    location: "Prince George",
    name: 'Anita Florence Thorne',
    blurb: 'Anita was 49 years old and her car was found at the Willow River rest area next to Highway 16. Her purse and all her belongings were found inside of the car but Anita has not been seen since.',
    photo: 'https://wordpress.thehueandcry.com/wp-content/uploads/anita-t.jpg',
  },
  {
    year: '2017',
    location: "Smithers",
    name: 'Frances Brown',
    blurb: 'Frances was last seen picking mushrooms with a companion, an activity she did every year. She was raised by a trapper and an experienced back country explorer, which made this disappearance unusual. Despite search efforts she was never seen again.',
    photo: 'https://wordpress.thehueandcry.com/wp-content/uploads/frances-brown.jpeg',
  },
  {
    year: '2018',
    location: "Terrace",
    name: 'Chantelle Catherine Simpson',
    blurb: 'Chantelle was 34 years old when she was reported missing after leaving her home on July 4th. Her abandoned car was found next to a gravel pit the next day. Days later her body was found in the Skeena River by a train conductor who was passing by.',
    photo: 'https://wordpress.thehueandcry.com/wp-content/uploads/chantel-image.png',
  },
  {
    year: '2018',
    location: "Smithers",
    name: 'Jessica Patrick Balczer',
    blurb: "Jessica was 18 years old when she dropped off her daughter with her grandmother for the night but never returned to pick her up.",
    link: 'https://thehueandcry.com/jessica-patrick-balczer',
    photo: 'https://wordpress.thehueandcry.com/wp-content/uploads/Jessica-Patrick-photo.jpeg',
  },
  {
    year: '2018',
    location: "Hazelton",
    name: 'Cynthia Martin',
    blurb: "Cynthia was 50 years old when she was last seen leaving her mother's house after 9pm. Her abandoned car was found days later off the shoulder of a road with all of her belongings inside. She has not been seen since.",
    photo: 'https://wordpress.thehueandcry.com/wp-content/uploads/cynthia-martin.png',
  },
];